##
## EPITECH PROJECT, 2024
## teams
## File description:
## Makefile
##

all:
		make -C ./libs/json
		make -C ./libs/utils
		make -C ./client
		make -C ./server

clean:
		make -C ./libs/json clean
		make -C ./libs/utils clean
		make -C ./client clean
		make -C ./server clean

fclean:
		make -C ./libs/json fclean
		make -C ./libs/utils fclean
		make -C  ./client fclean
		make -C ./server fclean

debug:
		make -C ./libs/json debug
		make -C ./libs/utils debug
		make -C ./client debug
		make -C ./server debug

re:
		make -C ./libs/json re
		make -C ./libs/utils re
		make -C ./client re
		make -C ./server re

.PHONY:	all clean fclean re debug
